import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Navbar, HomeWrapper, Main, Footer } from "../components";
import { useEffect } from "react";
import { IoLogoAppleAr } from "react-icons/io5";
import ReactDOM from "react-dom";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // if (typeof window === "undefined") {
  //   return <div>loading</div>;
  // }

  // useEffect(() => , [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeWrapper>
        <Navbar />
        <Main />
        <Footer />
      </HomeWrapper>
    </>
  );
}
